### ISSUE TITLE
Ps3 save compatibility?

### ISSUE THREAD

**Issue by Lassi22** [whampson/pigeon-locator#5]
Do you know, that would my ps3 save work with it? I literally miss 1 pigeon.

**Comment by whampson** [comment]
Send me your save and I'll see what I can do.

**Comment by missionfloyd** [comment]
If you're interested in adding xbox 360 compatibility, here's the saves.
[GTAIV 360 Saves.zip](https://github.com/whampson/pigeon-locator/files/4396401/GTAIV.360.Saves.zip)

**Comment by Lassi22** [comment]
Well, i did find the last one, but do you want to try to make ps3 save work
in your program? Sorry for a late reply.

ma 23. maalisk. 2020 klo 20.34 Wes Hampson <notifications@github.com>
kirjoitti:

**Comment by whampson** [comment]
> If you're interested in adding xbox 360 compatibility, here's the saves.

Awesome, thanks!

> but do you want to try to make ps3 save work in your program?

Yes please!

**Comment by Lassi22** [comment]
Okay, ill send you the file today.

su 29. maalisk. 2020 klo 5.52 Wes Hampson <notifications@github.com>
kirjoitti:

**Comment by Lassi22** [comment]
Here is the savefile directorys content. Good luck :)

su 29. maalisk. 2020 klo 5.52 Wes Hampson <notifications@github.com>
kirjoitti:

**Comment by missionfloyd** [comment]
PS3 saves will have to be decrypted using Bruteforce Savedata.

**Comment by Lassi22** [comment]
Good luck :)

ma 30. maalisk. 2020 klo 8.09 missionfloyd <notifications@github.com>
kirjoitti:

**Comment by whampson** [comment]
Hi @Lassi22, I never received your save. Did you try attaching it via email? I don't think that works.
Please upload the file to GitHub, GoogleDrive, MediaFire, etc. and send me the link.

Thanks

**Comment by Lassi22** [comment]
https://drive.google.com/file/d/1UA1yVamv_ReQ4oxP5EddNBZ8FfmDEMYN/view?usp=drivesdk
I hope that does the job. I never really use google drive

ma 30. maalisk. 2020 klo 23.08 Wes Hampson <notifications@github.com>
kirjoitti:

**Comment by whampson** [comment]
Hmm, says I need access. Can you turn on link sharing for that file? After that I should be able to view it.

**Comment by Lassi22** [comment]
Try it now

ma 30. maalisk. 2020 klo 23.15 Wes Hampson <notifications@github.com>
kirjoitti:

**Comment by whampson** [comment]
Got it, thanks.

Give me a week or so to see if I can get these to load.

**Comment by whampson** [comment]
Update: I've figured out the format for both PS3 saves (after decrypting) and 360 saves. Each store data in big-endian byte order, so I'll need to re-work the program a bit to be able to handle big-endian data. I've got some ideas on how to do this, I'm going to work on this over the next few days.

**Comment by Lassi22** [comment]
Thats cool!

pe 3. huhtik. 2020 klo 10.19 Wes Hampson <notifications@github.com>
kirjoitti:

**Comment by whampson** [comment]
I've got a pull request out for PS3 and Xbox 360 save support. Will be merging it and creating a new release in a few hours!

**Comment by missionfloyd** [comment]
I might as well mention that xbox 360 saves need to be extracted as well (the ones I posted were already extracted). [wxPirs](http://gael360.free.fr/wxPirs.php) is the probably the simplest tool for this.
